platform :ios, '10.0'
use_frameworks!

target 'LAKit' do
pod 'RxSwift',    '~> 4.0.0'
pod 'RxCocoa',    '~> 4.0.0'
pod 'SnapKit', '~> 4.0.0'
# pod 'AlamofireImage'
pod 'Alamofire', '~> 4.6.0'
pod 'SwiftDate', '~> 4.5.1'
pod 'Then'
# pod 'RealmSwift'

# pod 'Charts'
pod 'SwiftyJSON'
# pod 'PKHUD', '~> 5.0'
pod 'Moya'
pod 'Kingfisher'
pod 'IQKeyboardManagerSwift'
pod 'ESPullToRefresh'
# pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'
pod 'PopupDialog', '~> 0.6'
# pod 'Bugly'
# pod 'JPush'
#pod 'SwiftRichString'
# pod 'lottie-ios'
# pod 'Reveal-SDK', :configurations => ['Debug']
# pod 'RxGesture',:git => 'https://github.com/RxSwiftCommunity/RxGesture.git', :branch => 'master'
# pod 'KMPlaceholderTextView'
# pod 'Toucan'
# pod 'RainbowSwift', '~> 2.0'
# pod 'Log'
# pod 'EVReflection'
# pod 'HandyJSON'
# pod 'SwiftyBeaver'
# pod 'XCGLogger', '~> 5.0.1'
# pod 'Surge'
# pod 'BonMot'
# pod 'BadgeSwift', '~> 5.0'
#pod 'AutomaticStatusBarColor'
# pod 'SwiftyTimer'
# pod 'NVActivityIndicatorView'
# pod 'LBXScan', '~> 2.2'
# pod 'WechatOpenSDK'
# pod 'FSPagerView'
# pod 'Reveal-SDK', :configurations => ['Debug']
end

